"""empty message

Revision ID: 16ba9b733a27
Revises: 9de8b2878ba2
Create Date: 2024-12-04 22:59:43.208220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ba9b733a27'
down_revision = '9de8b2878ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amenidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabana_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cabana_id'], ['Cabana.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amenidades')
    # ### end Alembic commands ###
