"""empty message

Revision ID: 9d3c4c4e861e
Revises: 16ba9b733a27
Create Date: 2024-12-05 02:54:29.080400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d3c4c4e861e'
down_revision = '16ba9b733a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Amenidades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Amenidades',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cabana_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['cabana_id'], ['Cabana.id'], name='Amenidades_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
