"""empty message

Revision ID: 9de8b2878ba2
Revises: 8999b4d97ee3
Create Date: 2024-12-04 13:13:04.537034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9de8b2878ba2'
down_revision = '8999b4d97ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cabana', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=255), nullable=False))
        batch_op.drop_column('ubicacion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cabana', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###
