"""empty message

Revision ID: e8cf5364d1b2
Revises: 9d3c4c4e861e
Create Date: 2024-12-05 03:10:41.352110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8cf5364d1b2'
down_revision = '9d3c4c4e861e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CabanaAmenidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabana_id', sa.Integer(), nullable=False),
    sa.Column('amenidad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenidad_id'], ['Amenidad.id'], ),
    sa.ForeignKeyConstraint(['cabana_id'], ['Cabana.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Amenidad', schema=None) as batch_op:
        batch_op.drop_constraint('Amenidad_ibfk_1', type_='foreignkey')
        batch_op.drop_column('cabana_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Amenidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cabana_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Amenidad_ibfk_1', 'Cabana', ['cabana_id'], ['id'])

    op.drop_table('CabanaAmenidad')
    # ### end Alembic commands ###
